version: '3.8'

services:
  # ==========================================
  # SERVICIO 1: Base de Datos PostgreSQL
  # ==========================================
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-net
    # Healthcheck: El corazón de la estabilidad
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ==========================================
  # SERVICIO 2: Tu API Spring Boot
  # ==========================================
  api:
    build: .
    container_name: spring_api_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMIN_ADMIN_TOKEN=${ADMIN_ADMIN_TOKEN}
      - SPRING_DATASOURCE_URL=jdbc:${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
    networks:
      - backend-net
    # Dependencia Inteligente: Espera a que Postgres esté sano, no solo encendido
    depends_on:
      postgres-db:
        condition: service_healthy

# ==========================================
# RECURSOS GLOBALES (Volúmenes y Redes)
# ==========================================
volumes:
  pgdata:
    driver: local

networks:
  backend-net:
    driver: bridge